server:
  port: 8081

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: true
      path: /h2-console

camunda.bpm.admin-user:
  id: demo
  password: demo

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.web: INFO
  spring.mvc.log-request-details: true
