spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    org.springframework.jdbc: DEBUG
    com.mls.workflow: DEBUG