spring:
  datasource:
    url: jdbc:h2:mem:camunda-${random.uuid};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  datasource.hikari:
    maximum-pool-size: 2
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none


