spring:
  datasource:
    url: jdbc:h2:file:./data/camunda-db
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081

camunda.bpm.admin-user:
  id: demo
  password: demo